// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware-tanzu/nsx-operator/pkg/nsx/services/dns (interfaces: DNSRecordProvider)
//
// NOTE: mockgen v1.6.0 emits invalid syntax for sets.Set[types.NamespacedName]; this file was
// produced with mockgen then hand-corrected for generic type arguments. Prefer regenerating when
// upstream mockgen handles these signatures.

// Package mockdns is a generated GoMock package.
package mockdns

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dns "github.com/vmware-tanzu/nsx-operator/pkg/nsx/services/dns"
	endpoint "github.com/vmware-tanzu/nsx-operator/pkg/third_party/externaldns/endpoint"
	apitypes "k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/sets"
)

// MockDNSRecordProvider is a mock of DNSRecordProvider interface.
type MockDNSRecordProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDNSRecordProviderMockRecorder
}

// MockDNSRecordProviderMockRecorder is the mock recorder for MockDNSRecordProvider.
type MockDNSRecordProviderMockRecorder struct {
	mock *MockDNSRecordProvider
}

// NewMockDNSRecordProvider creates a new mock instance.
func NewMockDNSRecordProvider(ctrl *gomock.Controller) *MockDNSRecordProvider {
	mock := &MockDNSRecordProvider{ctrl: ctrl}
	mock.recorder = &MockDNSRecordProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSRecordProvider) EXPECT() *MockDNSRecordProviderMockRecorder {
	return m.recorder
}

// CreateOrUpdateRecords mocks base method.
func (m *MockDNSRecordProvider) CreateOrUpdateRecords(arg0 context.Context, arg1 *dns.AggregatedDNSEndponts) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateRecords", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateRecords indicates an expected call of CreateOrUpdateRecords.
func (mr *MockDNSRecordProviderMockRecorder) CreateOrUpdateRecords(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateRecords", reflect.TypeOf((*MockDNSRecordProvider)(nil).CreateOrUpdateRecords), arg0, arg1)
}

// DeleteRecordByOwnerNN mocks base method.
func (m *MockDNSRecordProvider) DeleteRecordByOwnerNN(arg0 context.Context, arg1, arg2, arg3 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordByOwnerNN", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRecordByOwnerNN indicates an expected call of DeleteRecordByOwnerNN.
func (mr *MockDNSRecordProviderMockRecorder) DeleteRecordByOwnerNN(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordByOwnerNN", reflect.TypeOf((*MockDNSRecordProvider)(nil).DeleteRecordByOwnerNN), arg0, arg1, arg2, arg3)
}

// ListRecordOwnerResource mocks base method.
func (m *MockDNSRecordProvider) ListRecordOwnerResource() map[string]sets.Set[apitypes.NamespacedName] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecordOwnerResource")
	ret0, _ := ret[0].(map[string]sets.Set[apitypes.NamespacedName])
	return ret0
}

// ListRecordOwnerResource indicates an expected call of ListRecordOwnerResource.
func (mr *MockDNSRecordProviderMockRecorder) ListRecordOwnerResource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecordOwnerResource", reflect.TypeOf((*MockDNSRecordProvider)(nil).ListRecordOwnerResource))
}

// ListReferredGatewayNN mocks base method.
func (m *MockDNSRecordProvider) ListReferredGatewayNN() sets.Set[apitypes.NamespacedName] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReferredGatewayNN")
	ret0, _ := ret[0].(sets.Set[apitypes.NamespacedName])
	return ret0
}

// ListReferredGatewayNN indicates an expected call of ListReferredGatewayNN.
func (mr *MockDNSRecordProviderMockRecorder) ListReferredGatewayNN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReferredGatewayNN", reflect.TypeOf((*MockDNSRecordProvider)(nil).ListReferredGatewayNN))
}

// ValidateEndpointsByZone mocks base method.
func (m *MockDNSRecordProvider) ValidateEndpointsByZone(arg0 string, arg1 *dns.ResourceRef, arg2 []*endpoint.Endpoint) ([]dns.EndpointRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateEndpointsByZone", arg0, arg1, arg2)
	ret0, _ := ret[0].([]dns.EndpointRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateEndpointsByZone indicates an expected call of ValidateEndpointsByZone.
func (mr *MockDNSRecordProviderMockRecorder) ValidateEndpointsByZone(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateEndpointsByZone", reflect.TypeOf((*MockDNSRecordProvider)(nil).ValidateEndpointsByZone), arg0, arg1, arg2)
}
